title = "BLOG getCode_"
baseURL = "https://blog.getcode.ml"
languageCode = "es-ES"
theme = "ananke"

DefaultContentLanguage = "es"
SectionPagesMenu = "main"
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  css = ["css/estilos.css"]
  favicon = "https://getcode.ml/src/logo.svg"
  site_logo = ""
  description = "Blog dedicado a la programación"
  facebook = "https://www.facebook.com/getcodeec/"
  twitter = ""
  instagram = "https://www.instagram.com/getcode_ec/"
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  whatsapp = "https://api.whatsapp.com/send?phone=593963886990&text=!Hola%C2%A1,%20estoy%20interesad@%20en%20getCode_"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-getcode"
  featured_image = "/images/backgroundGetCode_.png"
  recent_posts_number = 5

  [menu]
    [[menu.main]]
      identifier = "blog"
      name = "Blog"
      title = "Blog"
      url = "/blog/"
      weight = 0
    [[menu.main]]
      identifier = "contacto"
      name = "Contacto"
      title = "Contacto"
      url = "/contacto/"
      weight = 0

  [languages]
    [languages.es]
      title = "BLOG"
      weight = 1
      contentDir = "content/"